### ISSUE TITLE
Lemmy-ui Error when migrating 

### ISSUE THREAD

**Issue by SamuDifferent** [ubergeek77/Lemmy-Easy-Deploy#97]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

**Describe the issue**
> 
When trying to migrate from Version 0.19.3 to 0.19.5 i get this error code:

```
lemmy-ui-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lemmy-ui-1  | Error: Input buffer contains unsupported image format
lemmy-ui-1  |     at Sharp.toBuffer (/app/node_modules/.pnpm/sharp@0.33.4/node_modules/sharp/lib/output.js:161:17)
lemmy-ui-1  |     at /app/dist/js/server.js:2:3056385
lemmy-ui-1  |     at tryCatch (/app/node_modules/.pnpm/@babel+runtime@7.24.7/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
lemmy-ui-1  |     at Generator.<anonymous> (/app/node_modules/.pnpm/@babel+runtime@7.24.7/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
lemmy-ui-1  |     at Generator.next (/app/node_modules/.pnpm/@babel+runtime@7.24.7/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
lemmy-ui-1  |     at asyncGeneratorStep (/app/node_modules/.pnpm/@babel+runtime@7.24.7/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
lemmy-ui-1  |     at _next (/app/node_modules/.pnpm/@babel+runtime@7.24.7/node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
lemmy-ui-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Diagnostic Information**
> Run `./deploy.sh -d` and paste the output below:
```
==== Docker Information ====
Detected runtime: docker (Docker version 26.1.3, build b72abbb)
Detected compose: docker compose (Docker Compose version v2.27.0)
   Runtime state: OK

==== System Information ====
      OS: Linux
  KERNEL: 5.15.0-107-generic (x86_64)
HOSTNAME: OK
   SHELL: bash
  MEMORY:
               total        used        free      shared  buff/cache   available
Mem:           7.5Gi       2.5Gi       421Mi       149Mi       4.6Gi       4.6Gi
Swap:          4.0Gi       184Mi       3.8Gi

DISTRO:
----------------------------
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
----------------------------

==== Lemmy-Easy-Deploy Information ====
Version: 1.4.1

IMAGE                                   CREATED         STATUS
ghcr.io/ubergeek77/lemmy-ui:0.19.5      3 minutes ago   Up 3 minutes (unhealthy)
ghcr.io/ubergeek77/lemmy:0.19.5         3 minutes ago   Up 3 minutes
pgautoupgrade/pgautoupgrade:16-alpine   3 minutes ago   Up 3 minutes
asonix/pictrs:0.5                       3 minutes ago   Up 3 minutes

Integrity:
    28f529d2ce5f70966fb749412758eda00f24f135c177221a303a11318f778799  ./deploy.sh
    92c95dfc886792b8df2e9fffb540fc71a35c3bc6fd6c7662134da1545a79457a  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    2537678c7971df36c1ed95f4228d3cfcb15bb4a28a60d939eaf8dd75b5d64a36  ./templates/cloudflare.snip
    c494a610bcb4cd1cfc0a4fe4fb0f6d437b2a84a0ad1625daee240e6dd6f1c910  ./templates/compose-email-volumes.snip
    c9cb4c5fee12930e17798a02ae1bd12e2dc69e149a394c24511bc9d4e6b776d4  ./templates/compose-email.snip
    0ec8ceb82e1f9f6517a229d964c4949c3e0501019ab94cc62e6f8c29c2e56203  ./templates/docker-compose.yml.template
    1c202b1b6e87c65b2fcda6035c9fe3f8631d76662907ffd38f24b14686e30647  ./templates/lemmy-email.snip
    6f937ab0cbe01b0cc6f9428b18dde987529e690d4ca24a22027c002617539fda  ./templates/lemmy.hjson.template

Custom Files: 
*** No custom files ***

==== Settings ====
        CLOUDFLARE: Yes
 CADDY_DISABLE_TLS: true
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: true
         SMTP_PORT: 465
    ENABLE_POSTFIX: true
POSTGRES_POOL_SIZE: 5
POSTGRES_SHM_SIZE: 64m

==== Generated Files ====
Deploy Version: 0.19.3;0.19.3

total 44K
-rw-r--r-- 1 0 0    1 Jun 21 10:04 '2 ! such as credentials or IP addresses.'
drwxr-xr-x 2 0 0 4.0K Jun  2 21:59  caddy
-rw-r--r-- 1 0 0   28 Jun 21 10:03  caddy.env
-rw-r--r-- 1 0 0 2.2K Jun 21 10:03  docker-compose.yml
drwxr-xr-x 2 0 0 4.0K Jun 18 17:24  lemmy-ui-themes
-rw-r--r-- 1 0 0   50 Jun  2 21:59  lemmy.env
-rw-r--r-- 1 0 0  679 Jun 21 10:03  lemmy.hjson
-rw-r--r-- 1 0 0  106 Jun 21 09:58  pictrs.env
-rw-r--r-- 1 0 0   32 Jun 21 10:03  postfix.env
-rw-r--r-- 1 0 0   51 Jun  2 21:59  postgres.env
-rw-r--r-- 1 0 0   14 Jun  5 09:25  version

```

**Comment by ubergeek77** [comment]
It looks like you are running into this upstream issue, where the UI crashes if Pictrs is unreachable:

https://github.com/LemmyNet/lemmy-ui/issues/2113

Can you try manually removing the icon like in this issue, and see if a redeploy works?

Do your Pictrs logs have anything relevant?

```
docker compose -p lemmy-easy-deploy logs pictrs
```

**Comment by SamuDifferent** [comment]
I'm sorry, i don't really understand how i'm supposed to remove the Icon, given the code Provided in the issue.

And here the Pictrs Log:
```
pictrs-1  | 2024-06-21T10:03:31.085995Z  INFO pict_rs: Starting pict-rs on 0.0.0.0:8080
pictrs-1  | 2024-06-21T10:03:31.086136Z  INFO actix_server::builder: starting 8 workers
pictrs-1  | 2024-06-21T10:03:31.086194Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime

```

**Comment by SamuDifferent** [comment]
Thanks very much, it finally worked, after removing the icon with the code you just gave me. And yes, I pressed Ctrl+C, because it kept popping up more than a dozen times.

**Comment by ubergeek77** [comment]
Glad you got it working!

Thanks for reporting this, I really thought they fixed this 6 months ago...
